name: Feature Request
description: Suggest a new feature for Takutora System
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system would this feature affect?
      options:
        - Frontend (React)
        - Backend (Drupal)
        - API Integration
        - Authentication
        - Business Workflow
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or use case
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: Describe your proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other solutions have you considered?
      placeholder: Describe any alternative solutions or features you've considered

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups or screenshots

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
